const sources = 'AVO,ABFIRE,AU_BOM,BYU_ICE,BCWILDFIRE,CALFIRE,CEMS,EO,FEMA,FloodList,GDACS,GLIDE,InciWeb,IDC,JTWC,MRR,MBFIRE,NASA_ESRS,NASA_DISP,NOAA_NHC,NOAA_CPC,PDC,ReliefWeb,SIVolcano,NATICE,UNISYS,USGS_EHP,USGS_CMT,HDDS,DFES_WA';

module.exports = sources;